# Generated by Django 4.1.1 on 2022-09-05 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_image_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='caption',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='meme',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
