# Generated by Django 4.1 on 2022-09-06 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_meme_caption_alter_meme_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='image_url',
            field=models.CharField(default='Meme', max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
