# Generated by Django 4.1.1 on 2022-09-06 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_meme_caption_alter_meme_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='url',
            field=models.CharField(default='https://imgur.com/2vPFZhh', max_length=500),
        ),
    ]
