# Generated by Django 4.1.1 on 2022-09-06 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_meme_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='url',
            field=models.CharField(default='', max_length=400),
        ),
    ]
