# Generated by Django 4.1.1 on 2022-09-06 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_meme_image_url_delete_photo'),
        ('main_app', '0006_meme_url'),
    ]

    operations = [
    ]
