# Generated by Django 4.1 on 2022-09-08 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_meme_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='date',
            field=models.CharField(default=datetime.datetime(2022, 9, 8, 16, 44, 16, 574501, tzinfo=datetime.timezone.utc), max_length=10),
        ),
    ]
