# Generated by Django 4.1 on 2022-09-09 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_alter_meme_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 9, 9, 11, 53, 48, 221373, tzinfo=datetime.timezone.utc)),
        ),
    ]
